name: Cypress Tests
on: 
  workflow_dispatch:
  pull_request:
      branches: [main]
jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    # defaults:
    #   run:
    #     working-directory: cypress

    name: Cypress workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start hacker challenge server locally
        run: python3 -m http.server &

      # - name: debug directory
      #   run: pwd
      
      - name: Cypress run tests
        uses: cypress-io/github-action@v6 # will take care of running `npm ci`
        with:
          # start: cd .. & python3 -m http.server
          # wait-on: 'http://localhost:8000'
          command: npm run cypress-chrome  
          working-directory: cypress # needs to be configured here, see https://github.com/cypress-io/github-action#working-directory

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report
          path: reports/mocha/
          retention-days: 30
