name: Cypress Tests
on: 
  workflow_dispatch:
  pull_request:
      branches: [main]
jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    name: Cypress workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start hacker challenge server locally
        run: python3 -m http.server &

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cypress dependencies
        working-directory: cypress-automation
        run: npm ci

      - name: Run Cypress tests
        working-directory: cypress-automation
        run: npm run cypress:ci

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report
          path: cypress/reports/mocha/
          retention-days: 30
